leftnav:
- identifier: 6fe7b50b-8d5d-460d-a8b6-ca0862b37619
  name: About the Course
  url: /pages/syllabus
  weight: 10
- identifier: external-1809050890-1676410050256
  name: 'Fall 2022 Course '
  url: https://computationalthinking.mit.edu/Fall22/
  weight: 20
